### ISSUE TITLE
Les Données de Fonction et de Secteur semble être interverties 

### ISSUE THREAD

**Issue by Ambrelaoh** [pebble-solutions/App-RH-drh#46]
![Capture d’écran du 2024-02-12 09-30-49](https://github.com/pebble-solutions/App-RH-drh-frontend/assets/130644994/3ebb19ff-7a1b-4d9b-ad9b-12f811cb2868)

**Comment by Guillaume35** [comment]
C'est eux qui ont souhaité ça comme ça. Il ne s'agit pas d'un bug dans la mesure ou tu peux écrire ce que tu veux dans les fonctions.

**Comment by killiankopp** [comment]
si c'est le fonctionnement normal... on ferme
Dans les futures apps ce genre de lsite sera enregistrée à la fois dans une liste qui sera modifiable pour guider l'utilisateur mais aussi sur chaque enregistrement pour palier au fait que la liste peut évoluer au cours du temps.
