### ISSUE TITLE
pour un utilisateur en particulier, je ne peux pas lui donner un accès pointage

### ISSUE THREAD

**Issue by Ambrelaoh** [pebble-solutions/App-RH-drh#49]
Pour un utilisateur, je ne peux pas lui donner d'accès pointage, ça me met que le compte existe déjà.
![Capture d’écran du 2024-02-12 10-03-33](https://github.com/pebble-solutions/App-RH-drh-frontend/assets/130644994/80acc3f9-2a3f-4061-83bd-b18f42722d79)
Le lien de où l'erreur a lieu : https://drh.pebble.solutions/#/personnel/120/account/create-team-clock-access

**Comment by Guillaume35** [comment]
si le compte existe déjà, il faut juste le rattacher

**Comment by killiankopp** [comment]
idem issue 48

**Comment by Ambrelaoh** [comment]
oui, mais je n'arrive pas à lui attribuer l'utilisateur tablette, ou alors je ne sais pas faire ?

**Comment by Ambrelaoh** [comment]
Dans ce cas, la solution est simple. Il n'existe aucune option dans l'appli DRH pour le faire. Il suffit de retourner dans l'ancienne interface.
